return {
  'tpope/vim-sleuth',
  require 'plugins.git',
  require 'plugins.comment',
  require 'plugins.telescope',
  require 'plugins.dashboard-nvim',
  require 'plugins.nerdy',
  require 'plugins.nvim-lspconfig',
  require 'plugins.venv-selector',
  require 'plugins.conform',
  require 'plugins.nvim-cmp',
  require 'plugins.tokyonight',
  -- require 'plugins.onedark',
  -- require 'plugins.seoul256',
  require 'plugins.todo-comments',
  require 'plugins.mini',
  require 'plugins.treesitter',
  require 'plugins.lualine',
  require 'plugins.neo-tree',
  require 'plugins.prettier',
}
